### ISSUE TITLE
Sport items like “Climbing site“ don't match in Vespucci

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#458] opened 2024-06-22 15:47 UTC
Your new item “Climbing site“ (`sport=climbing`) doesn't match if a node is tagged like that (which is fine e.g. for artificial climbing walls according to the [Wiki](https://wiki.openstreetmap.org/wiki/Climbing)). The result is: no icon on the map, no matching in the editor.

![sport_climbing_21005](https://github.com/simonpoole/beautified-JOSM-preset/assets/48966999/d22474fd-3062-4d79-a4b0-9f3b2ccb4e25)

I think ”sport” could be added to the `object_keys` – then also other sport items (like “Soccer“) will match (although they should have a main tag like `leisure=pitch`, `leisure=sports_centre` or `leisure=stadium` according to the [Wiki](https://wiki.openstreetmap.org/wiki/Tag:sport%3Dsoccer)).

Or – if `sport=climbing` should be seen as an exception (can also be used _without_ a main `leisure=* `tag) – then perhaps `object=true` could be added in its item. I tried it out and this also worked.

**Comment by simonpoole** [comment] 2024-06-22 16:58
Duplicate of https://github.com/simonpoole/beautified-JOSM-preset/issues/453

**Closed** 2024-06-22 16:58 UTC

**Comment by jajajaneeneenee** [comment] 2024-06-30 16:53
Not planned ... OK ...

It would still be nice to get some feedback on whether you also see a problem with it or why not (for Vespucci).

Because I don't quite understand the concept of items like "Climbing site" (fixed key-value pair sport=climbing) for Vespucci. You can find the item in the list in the editor (or of course by preset search for "Climbing, but after you have assigned it to a new node, for example, you don't see an icon on the map, nor does the item match in the editor when you call up the node again to edit it.

And there is also no warning/information message that, for example, a main tag such as leisure=pitch or the like is missing.

In JOSM it is fundamentally different, as there is a kind of "multiple matching" for all items with matching fixed key-value pairs). And a node tagged only with sport=climbing is also displayed with a climbing icon on the map. (When uploading, there is then the validator warning "missing tag - sport without physical feature").

For Vespucci, I see a conceptual gap here.

Perhaps one could think about a kind of "second level matching" for Vespucci with an appropriate fixed key-value pair without a "real" ("is object") match of an item (perhaps with a validator warning "main tag missing"?), but with matching of such an item when editing - comparable to JOSM - (with a special, e.g. different colored warning display when editing?) Or another solution...

And the case of "sport=climbing" _without_ a main tag has crossed my path several times now (in the real world), especially with climbing walls on buildings – and for that reason it is currently described in the wiki _without_ a leisure main tag (as the only sport tag as far as I know). But it results in Osmose error messages, for example. I have already thought about whether one should assign leisure=pitch for such cases and view the climbing wall as a kind of "vertical sports field", which is what it actually is – if necessary, it could also be described like this in the wiki and this "exception" would be eliminated. Individual table tennis tables, for example, are also tagged with leisure=pitch ... so “pitch” is already being interpreted broadly.

Which does not solve the problem with the (non-)matching of the sport items in Vespucci if a main tag is missing ...

**Comment by simonpoole** [comment] 2024-06-30 16:58
The thin you missed is "Duplicate of https://github.com/simonpoole/beautified-JOSM-preset/issues/453"*

**Comment by jajajaneeneenee** [comment] 2024-07-02 23:50
Don't understand what you mean ... #453 is about Climbing routes. That's why I also didn't understand why it's a duplicate.
