### ISSUE TITLE
Barrier icon missing

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#402] opened 2023-08-11 13:41 UTC
Here the user is faced with a choice of two things that are called the same, but the left one doesn't have an icon. Upon investigation it seems the left one is for a barrier ditch. But there is no barrier icon yet.

![Screenshot_20230811_083650_Vespucci.jpg](https://github.com/simonpoole/beautified-JOSM-preset/assets/1230959/07f8dd3d-2549-4df8-aa32-bbc673df6203)

**Comment by simonpoole** [comment] 2023-08-11 13:59
Duplicate of https://github.com/simonpoole/beautified-JOSM-preset/issues/4 Naturally there is nothing stopping you from creating an icon.

**Closed by simonpoole** 2023-08-11 13:59 UTC
