### ISSUE TITLE
Searching for workshop should also find shed

### ISSUE THREAD

**Issue by jidanni** [simonpoole/beautified-JOSM-preset#365] opened 2023-02-25 10:27 UTC
https://wiki.openstreetmap.org/wiki/Tag:building%3Dshed says it is also a workshop, but we only find ocial workshops when searching with the word workshop.

**Comment by simonpoole** [comment] 2023-02-25 19:00
Duplicate of https://github.com/simonpoole/beautified-JOSM-preset/issues/366

**Closed** 2023-02-25 19:00 UTC
