### ISSUE TITLE
problems with checkgroups without text attribute in Vespucci (including crashes!)

### ISSUE THREAD

**Issue by jajajaneeneenee** [simonpoole/beautified-JOSM-preset#196] opened 2020-08-25 01:29 UTC
I experienced a lot of crashes of Vespucci when I tried to edit bollards, lift gates, swing gates and decided to check the vespucci_preset.xml (v1.9.6), And I found the following problems – and in every case, the problems disappeared if I added a text="xyz" attribute to the `<checkgroup>`.

This is perhaps more a Vespucci bug (?), but I decided to report it here. I didn’t check what happens in JOSM and I don’t know if checkgroups always MUST have a text attribute or if it’s optional (but it makes sense that they have one).

**First problem (only a cosmetic, but strange thing):**

The item "Cycle Barrier" has a checkgroup for key="foot" and key="horse" without a text attribute (at the checkgroup). Vespucci (v15.0.2) surprisingly displays the text "Used in some countries for a named road junction" which seems to come from the code line:

            `<label text="Used in some countries for a named road junction who.s name serves for local orientation."/>`

... of item name="Named Junction“, which is the last label text before the "Cycle Barrier" code lines. (And the only occurrence of this text in the xml file.) This is very strange, specially because the [Vespucci tutorial](http://vespucci.io/tutorials/presets/) says for `<label>` "support=ignored".

![Screenshot_cycle_barrier](https://user-images.githubusercontent.com/48966999/91110931-7cf6b700-e67f-11ea-89c1-fef0be06e316.jpg)

Other affected items are:
	•	"Wash" (wrong text "Authentication:" comes from item name="Charging Station")
	•	"Campsite" (wrong text: "Stop types")
	•	"Camp pitch" (here NO checkgroup is displayed, but single checkbox lines!)
	•	"Goods conveyor" (wrong text "Games:")

![Screenshot_car_wash](https://user-images.githubusercontent.com/48966999/91111012-a9aace80-e67f-11ea-9729-d5a4e5c0c999.jpg)  ![Screenshot_camp_site](https://user-images.githubusercontent.com/48966999/91110985-9dbf0c80-e67f-11ea-844e-f5ce266a4a96.jpg)

![Screenshot_camp_pitch](https://user-images.githubusercontent.com/48966999/91110998-a3b4ed80-e67f-11ea-972a-ed22311a7809.jpg)  ![Screenshot_goods_conveyor](https://user-images.githubusercontent.com/48966999/91110967-913ab400-e67f-11ea-8b2f-5d752ad4106b.jpg)

**Second (serious) problem:**

Vespucci (v15.0.2) **crashes** on my device (Huawei Honor 7X with Android 9.1.0) e.g. with barrier=bollards, barrier=lift_gate and others if checkboxes for foot=yes (or bicycle=yes, horse=yes, motorcar=yes …) are set and I try to edit such a node.

This seems to come from the referenced `<chunk id="check_access_nomotor“>` and `<chunk id="check_access_motor“>` – both have checkgroups without a text attribute. If I add text attributes there, Vespucci does not crash anymore.

Here the code  which seems to cause a Vespucci crash:

```
    <chunk id="check_access_nomotor">
        <optional text="Non-motorized traffic:">
            <checkgroup columns="3">
                <check key="foot" text="Foot" />
                <check key="bicycle" text="Bicycle" />
                <check key="horse" text="Horse" />
            </checkgroup>
            <space />
            <reference ref="wheelchair" />
        </optional>
    </chunk>
```

And with this code everything is fine (`<optional>` text is not displayed in Vespucci, but no problem):

```
    <chunk id="check_access_nomotor">
        <optional text="Non-motorized traffic:">
            <checkgroup text="Non-motorized traffic" columns="3">
                <check key="foot" text="Foot" />
                <check key="bicycle" text="Bicycle" />
                <check key="horse" text="Horse" />
            </checkgroup>
            <space />
            <reference ref="wheelchair" />
        </optional>
    </chunk>
```

**Note:** I think, the crash comes from the fact, that there **no** `<label>` code line before `<chunk id="check_access_nomotor">` (line 253) and `<chunk id="check_access_motor">` (line 272) ... I made a test with another checkgroup in a chunk code (with a label code line before), and then also the last label text was displayed (and no crash) .... Anyway ... this should be fixed I think.

**Comment by simonpoole** [comment] 2020-08-25 05:30
Did you submit a crash dump for the crash?

The oddity with the labels is that there is a hack that will try to use a preceding label if text is not set on a checkgroup (this however should always be the case in this preset, it is really just a workaround for JOSM compatibility).

**Comment by simonpoole** [comment] 2020-08-25 07:29
> 
> 
> I experienced a lot of crashes of Vespucci when I tried to edit bollards, lift gates, swing gates and decided to check the vespucci_preset.xml (v1.9.6), And I found the following problems – and in every case, the problems disappeared if I added a text="xyz" attribute to the `<checkgroup>`.
> 
> This is perhaps more a Vespucci bug (?), but I decided to report it here. I didn’t check what happens in JOSM and I don’t know if checkgroups always MUST have a text attribute or if it’s optional (but it makes sense that they have one).
> 
> **First problem (only a cosmetic, but strange thing):**

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/26c132774cd3ad41c01092bd21e7168670dec978 as already mentioned if there is a label immediately preceding the checkgroup  it will use the text from that if no text attribute is set for the checkgroup element. This is a common pattern in JOSM presets and makes sense, the bug was caused by the label value not being removed if not immediately used. 

If no text value at all can be determined, the checkboxes are displayed as individual checks, naturally most of the time this should be present and there were a couple missing, fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/2fc42bb9f39a9b2f136c7ec1b5f125e52d2b9385

> **Second (serious) problem:**
> 
 This was likely "always" broken, but didn't cause an issue before the last preset update, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/615249cbc48b7c8a904ad58cd296833365067b55 


Thanks for the report. Note that it is better to split things up in to individual reports, in particular when they span multiple repos. For example somebody experiencing a crash in Vespucci due to the issue above will not be able to find a corresponding issue there, which is where they would likely look first.

**Closed by simonpoole** 2020-08-25 07:29 UTC

**Comment by jajajaneeneenee** [comment] 2020-08-30 00:44
Hello!

Great that it is fixed!

And yes, I submitted several crash dumps (you mean the crash reports you can send after a crash? I mean that ...), before I checked the preset xml file (when trying to edit barriers like lift gates and so on and I didn't know why).

And yes, in the future I will try to split up the reports for the different repos ... I was too much concentrated on your preset xml and so I only wrote it here.
